name: Build and Deploy
on:
  push:
  release:
    types:
      - published

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: |
        go build ./...
  deploy:
    name: Setup, Create Docker Image, and Publish
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GITHUB_SHA: ${{ github.sha }}
      ORGANISATION: dustedcodes
      IMAGE: grpc-test
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Build & Publish the Docker image
    - name: Build and Publish
      run: |
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        PATTERN="refs/tags/v"
        SUB=""
        TAG="${GITHUB_REF/$PATTERN/$SUB}"
        docker build -t "$ORGANISATION"/"$IMAGE":"$TAG" .
        docker push "$ORGANISATION"/"$IMAGE":"$TAG"